28 26 implement nav bar is soft blocked by react router issue
UniversityOfSaskatchewanCMPT371/term-project-2024-team-3 pull request #35
Opened 2024-01-25 22:29 UTC by glenntanjoh

Removed routes and added navbar. Left comments in on how to add consequent pages.

2024-01-25 23:41 UTC, ralphgregorio requested changes
I think it looks good, but I just have some comments on naming/styling conventions

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/App.test.tsx
> +  expect(homeLink).toBeInTheDocument();
Don't have to change anything here but just wanted to point out an easier shortcut.

you can get getByText from render

so you can do const { getByText } = render ( <Router> <Navbar /> </Router>)

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/App.test.tsx
> +  expect(fileUploadLink).toBeInTheDocument();
You don't have to change anything here as well but there is a shortcut. 
```suggestion
  getByText(/FILE UPLOAD/i);
```
Calling `getByText()` itself already does the equivalent of `expect(fileUploadLink).toBeInTheDocument();` so you can do this in future tests to make life easier

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/components/navbar.tsx
> +function Navbar(): React.ReactElement {
Please rename the file as `Navbar.tsx` Naming conventions for react `.tsx` files should always begin with capital letter

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/App.tsx
> +        {/* <Route element={<RequireAuth type={"user"} />}></Route> */}
I know I made you remove my FileUpload Page earlier but could you link the route for it here as well since your branch now contains my changes

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/tests/navbar.test.tsx
> +import React from "react";
Could You rename this file as Navbar.test.tsx

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/components/navbar.tsx
> +function Navbar(): React.ReactElement {
Can you also put Navbar to its own folder called `Navbar` just for organization sake

2024-01-25 23:41 UTC, ralphgregorio commented on frontend/src/tests/navbar.test.tsx
> +import React from "react";
Also please move this test file to the same location as the component its testing. My reasoning for this is its easier to keep to update tests when the test file is in the same location as the component it is testing. Also makes it easier to find the corresponding test files when we are updating logic within the components

2024-01-26 00:07 UTC, cameronbeattie306 commented
When Ralph's suggestions are implemented I'll approve of the PR too

2024-01-26 01:01 UTC, ralphgregorio approved these changes
thanks for making the changes!

2024-01-26 01:15 UTC, cameronbeattie306 commented
Looks good!

2024-01-26 01:15 UTC, cameronbeattie306 approved these changes
Looks good

2024-01-26 01:20 UTC, merged